# Generated by Django 4.2.2 on 2023-08-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=50)),
                ('company_type', models.CharField(choices=[('IT', 'IT'), ('NON IT', 'NON IT'), ('None', 'None')], max_length=50)),
                ('company_about', models.CharField(max_length=50)),
                ('company_crated', models.DateTimeField(auto_now=True)),
                ('company_active', models.BooleanField(default=False)),
            ],
        ),
    ]
