# Generated by Django 4.2.2 on 2023-08-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_email', models.CharField(max_length=50)),
                ('employee_address', models.CharField(max_length=50)),
                ('employee_phone', models.CharField(max_length=50)),
                ('employee_about', models.CharField(max_length=50)),
                ('employee_position', models.CharField(choices=[('manager', 'manager'), ('software developer', 'software developer'), ('project manager', 'project manager')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
